kubectl apply -f docker-dind-claim1-persistentvolumeclaim.yaml
kubectl apply -f docker-dind-deployment.yaml
kubectl apply -f docker-dind-persistentvolumeclaim.yaml
kubectl apply -f grafana-conf-persistentvolumeclaim.yaml
kubectl apply -f grafana-deployment.yaml
kubectl apply -f grafana-home-persistentvolumeclaim.yaml
kubectl apply -f grafana-service.yaml
kubectl apply -f influxdb-deployment.yaml
kubectl apply -f influxdb-persistentvolumeclaim.yaml
kubectl apply -f influxdb-service.yaml
kubectl apply -f influxdb-timeshift-proxy-claim0-persistentvolumeclaim.yaml
kubectl apply -f influxdb-timeshift-proxy-deployment.yaml
kubectl apply -f influxdb-timeshift-proxy-service.yaml
kubectl apply -f jenkins-claim1-persistentvolumeclaim.yaml
kubectl apply -f jenkins-claim3-persistentvolumeclaim.yaml
kubectl apply -f jenkins-deployment.yaml
kubectl apply -f jenkins-home-persistentvolumeclaim.yaml
kubectl apply -f jenkins-service.yaml
kubectl apply -f jmeter-deployment.yaml
kubectl apply -f portainer-claim0-persistentvolumeclaim.yaml
kubectl apply -f portainer-deployment.yaml
kubectl apply -f portainer-service.yaml
kubectl apply -f telegraf-claim0-persistentvolumeclaim.yaml
kubectl apply -f telegraf-deployment.yaml
