kubectl delete -f docker-dind-claim1-persistentvolumeclaim.yaml
kubectl delete -f docker-dind-deployment.yaml
kubectl delete -f docker-dind-persistentvolumeclaim.yaml
kubectl delete -f grafana-conf-persistentvolumeclaim.yaml
kubectl delete -f grafana-deployment.yaml
kubectl delete -f grafana-home-persistentvolumeclaim.yaml
kubectl delete -f grafana-service.yaml
kubectl delete -f influxdb-deployment.yaml
kubectl delete -f influxdb-persistentvolumeclaim.yaml
kubectl delete -f influxdb-service.yaml
kubectl delete -f influxdb-timeshift-proxy-claim0-persistentvolumeclaim.yaml
kubectl delete -f influxdb-timeshift-proxy-deployment.yaml
kubectl delete -f influxdb-timeshift-proxy-service.yaml
kubectl delete -f jenkins-claim1-persistentvolumeclaim.yaml
kubectl delete -f jenkins-claim3-persistentvolumeclaim.yaml
kubectl delete -f jenkins-deployment.yaml
kubectl delete -f jenkins-home-persistentvolumeclaim.yaml
kubectl delete -f jenkins-service.yaml
kubectl delete -f jmeter-deployment.yaml
kubectl delete -f portainer-claim0-persistentvolumeclaim.yaml
kubectl delete -f portainer-deployment.yaml
kubectl delete -f portainer-service.yaml
kubectl delete -f telegraf-claim0-persistentvolumeclaim.yaml
kubectl delete -f telegraf-deployment.yaml
